[package]
name = "rust_kvs"
version.workspace = true
edition.workspace = true

[dependencies]
adler32.workspace = true
tinyjson.workspace = true

[dev-dependencies]
tempfile = "3.20"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
